In [1]:
M = 3
N = 4

numOfPorts = 4
maxlength = 5

configMap = [
    ["A1", "B1", "C1", "D1"],
    ["A2", "B2", "C2", "C5"],
    ["A3", "A4", "C3", "C4"],
]


In [2]:
import numpy as np

def getPortIndex(code: str) -> int:
    return ord(code[0]) - ord("A")

def returnHardwareMatrix(unity: np.ndarray) -> np.ndarray:
    global M, N, numOfPorts, maxlength, unityToHardware
    hardwareMatrix = np.zeros((maxlength, numOfPorts), dtype=tuple)
    hardwareMatrix.fill(None)
    
    for i in range(M):
        for j in range(N):
            hardwareMatrix[unityToHardware[i, j]] = unity[i, j]

    return hardwareMatrix

def returnUnityMatrix(hardware: np.ndarray) -> np.ndarray:
    global M, N, numOfPorts, maxlength, hardwareToUnity
    unityMatrix = np.zeros((M, N), dtype=tuple)
    unityMatrix.fill(None)
    
    for i in range(maxlength):
        for j in range(numOfPorts):
            if hardwareToUnity[i, j] is not None:
                unityMatrix[hardwareToUnity[i, j]] = hardware[i, j]

    return unityMatrix

unityToHardware = np.zeros((M, N), dtype=tuple)
hardwareToUnity = np.zeros(( maxlength, numOfPorts), dtype=tuple)
hardwareToUnity.fill(None)
for i in range(M):
    for j in range(N):
        unityToHardware[i, j] = (int(configMap[i][j][1:])-1, getPortIndex(configMap[i][j]))
        hardwareToUnity[int(configMap[i][j][1:])-1, getPortIndex(configMap[i][j])] = (i, j)


In [3]:
test_unity = np.arange(M*N).reshape(M, N)
print("test_unity:\n", test_unity)
print("returnHardwareMatrix:\n", returnHardwareMatrix(test_unity))
print()

test_hardware = np.arange(maxlength*numOfPorts).reshape(maxlength, numOfPorts)
print("test_hardware:\n", test_hardware)
print("returnUnityMatrix:\n", returnUnityMatrix(test_hardware))

test_unity:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
returnHardwareMatrix:
 [[0 1 2 3]
 [4 5 6 None]
 [8 None 10 None]
 [9 None 11 None]
 [None None 7 None]]

test_hardware:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
returnUnityMatrix:
 [[0 1 2 3]
 [4 5 6 18]
 [8 12 10 14]]
